### ISSUE TITLE
Segfault during launch

### ISSUE THREAD

**Issue by mclane** [digidigital/OCRthyPDF-Essentials#17]
Hello,
I am trying to run ocrthypdf on a Manjaro Linux system with kernel 6.0.2. Installation is done via snap. When launching ocrthypdf, I get the following segfault:
``ocrthypdf -- log DEBUG   
/snap/ocrthypdf/110/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3-0/gtk-query-immodules-3.0: symbol lookup error: /snap/ocrthypdf/110/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0: undefined symbol: pango_font_family_get_face
ERROR: /snap/ocrthypdf/110/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3-0/gtk-query-immodules-3.0 exited abnormally with status 127
/snap/ocrthypdf/110/snap/command-chain/desktop-launch: line 26: 27173 Segmentation fault      (core dumped) "$@"
ERROR: /snap/ocrthypdf/110/gnome-platform/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/gdk-pixbuf-query-loaders exited abnormally with status 139
Speicherzugriffsfehler (Speicherabzug geschrieben)
`` 
Looks like a problem with snap? Or do I need to downgrade the kernel?

**Comment by mclane** [comment]
Problem disappeared after reboot. Strange.

**Comment by digidigital** [comment]
Thx for reporting it anyway. 

I was just about to get on it and see if I could identify the cause for the error.
