### ISSUE TITLE
snap package installed size

### ISSUE THREAD

**Issue by jensb** [digidigital/OCRthyPDF-Essentials#21]
Hello,
the current snap package - at least when installing it on Ubuntu 22.04 - is over 700 MB in size.
Is this intentional? This seems waaaaay overblown for a simple GUI of a command line utility.

**Comment by digidigital** [comment]
Hi jensb,

as you know SNAP is a container that brings all the dependencies and dependencies of the dependencies.
The python script itself is tiny but the SNAP ships with it's own python, needed modules, ocrmypdf, ghostscript, tesseract5, it's dependencies and all languages (~1,5MB - 20 MB each).
I could remove some testdata and some unused libs but the main driver are the language files.

If size matters I suggest to simply use the two python scripts in the code directory of this repository.

**Comment by jensb** [comment]
I understand. Here's how I got it running:

    $ wget https://raw.githubusercontent.com/digidigital/OCRthyPDF-Essentials/main/code/OCRthyPDF.py
    # Remove the 'Read Licenses' block (5 lines) from downloaded OCRmyPDF.py
    $ sudo apt install python3-tk unpaper
    $ sudo pip3 install pysimplegui darkdetect
    
This adds about 5 MB of files to my system, instead of 700 MB, and also works fine.
Of course, you don't get desktop integration and all that but I can create a menu item manually.
Thanks!
