### ISSUE TITLE
ocrmypdf returns error "invalid arguments"

### ISSUE THREAD

**Issue by WAKIGA98** [digidigital/OCRthyPDF-Essentials#22]
I've used OCRthyPDF for about two years, last time on Monday. Today (Sunday), the software returns an error message.
During the last week there has been a system update.
"start OCR" of any pdf file returns the error.

OS: Ubuntu 22.04.4 LTS

Running on CMD with DEBUG:

> INFO:OCRthyPDF:OCR job started/home/..../name.pdf
> DEBUG:OCRthyPDF:Job Exit-Code: Invalid arguments, exited with an error.
> INFO:OCRthyPDF:Cleanup complete.

Output in "Console":

> ocrmypdf --use-threads -l deu -l eng --skip-text --tesseract-thresholding otsu --rotate-pages --rotate-pages-threshold 15 --optimize 1 --output-type pdfa-2 name.pdf name_OCR.pdf
> 
> Traceback (most recent call last):
> 
>   File "/snap/ocrthypdf/161/bin/ocrmypdf", line 5, in <module>
> 
>     from ocrmypdf.__main__ import run
> 
>   File "/snap/ocrthypdf/161/lib/python3.9/site-packages/ocrmypdf/__init__.py", line 10, in <module>
> 
>     from ocrmypdf import helpers, hocrtransform, pdfa, pdfinfo
> 
>   File "/snap/ocrthypdf/161/lib/python3.9/site-packages/ocrmypdf/pdfinfo/__init__.py", line 9, in <module>
> 
>     from ocrmypdf.pdfinfo.info import Colorspace, Encoding, PageInfo, PdfInfo
> 
>   File "/snap/ocrthypdf/161/lib/python3.9/site-packages/ocrmypdf/pdfinfo/info.py", line 23, in <module>
> 
>     from pikepdf import (
> 
> ImportError: cannot import name 'PdfMatrix' from 'pikepdf' (/snap/ocrthypdf/161/lib/python3.9/site-packages/pikepdf/__init__.py)
> 
> Invalid arguments, exited with an error.

**Comment by digidigital** [comment]
Thx for reporting the issue. It seems pikepdf got an update and removed the 'PdfMatrix'
I set the pikepdf-version to v8.15.1 and the issue should be gone.

...might be a good idea to switch the base snap to core24 (based on 24.04 LTS) in order to be able to use all the latest dependencies. Maybe I start the migration next weekend.

**Comment by digidigital** [comment]
Issue should be fixed with SNAP-release:  
latest/stable | 16 Jun 24
Revision: 162
Version: v0.7.0-62-g6b8e7c4 
Build: lp-89838965

**Comment by WAKIGA98** [comment]
Thank you very much!
I run the update and problem fixed.
