### ISSUE TITLE
Leptonica is not correctly linked in the snap

### ISSUE THREAD

**Issue by alexanderlanganke** [digidigital/OCRthyPDF-Essentials#5]
The snap will not work out of the box. 
On a fresh Ubuntu install without any manually included libs the app will return the following error:

 Tesseract is not installed properly, we can't find the installation on your system PATH variable.
The library we are looking for is usually called:
liblept*.so

This is an error message generated by OCRmyPDF. -> leptonica.py generates this.
I sent you an email with a screenshot.

**Comment by alexanderlanganke** [comment]
This was suggested as a solution here:
https://forum.snapcraft.io/t/trouble-getting-a-pip-package-to-work-as-a-snap/25077/6

```
environment:
...
LD_LIBRARY_PATH: $SNAP/usr/lib/x86_64-linux-gnu
...
```

Does NOT fix the issue unfortunately

**Comment by digidigital** [comment]
Fixed as suggested by James Carroll
