### ISSUE TITLE
macOS package

### ISSUE THREAD

**Issue by LyzardKing** [digidigital/OCRthyPDF-Essentials#9]
Hi! I find your program very useful, so I decided make it available on macOS via homebrew, so my colleagues could use it.
At the moment it's available on a repo under my name, but I would like to add it to the homebrew repository if you agree.
For now it can be downloaded from https://github.com/LyzardKing/homebrew-lk
The only issue is that it still has to be started from the cli (although one could add a custom icon in the Applications folder..)

**Comment by digidigital** [comment]
Hi Galileo! 
Thanks for the positive feedback. 
If everything is working as on Linux please feel free to add OCRthyPDF to the homebrew repository.
:thumbsup:

**Comment by LyzardKing** [comment]
@digidigital I haven't gotten around to publishing on the upstream brew repo, but it works on mine.
I have to look at the requirements for the brew repository.

I'll give it a go
